spring:
  application:
    name: AUTHENTICATION
  datasource:
    username: postgres
    password: postgres
    url: "jdbc:postgresql://localhost:5432/sbs_authentication"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8081

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

